baseURL = 'http://huyhung0.github.io/notes/'
languageCode = 'en-us'
title = 'Notes'
theme = "hugo-book"

[markup.goldmark.renderer]
  unsafe = true

[markup.tableOfContents]
#  startLevel = 1

[params]
  BookTheme = 'light' #'dark', 'auto'

