baseURL = 'http://huyhung0.github.io/notes/'
languageCode = 'en-us'
title = 'Notes'
theme = "hugo-book"


[markup]
[markup.goldmark.renderer]
  unsafe = true

[markup.tableOfContents]
  startLevel = 2
  ordered = true
  endLevel = 5

[markup.highlight]
  hl_Lines = ''
  hl_inline = false
  lineAnchors = ''
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = true
  style = 'monokai'
  # https://xyproto.github.io/splash/docs/all.html
  # https://xyproto.github.io/splash/docs/longer/all.html
  #style = 'api'
  #style = 'bash'




[params]
  BookTheme = 'light' #'dark', 'auto'



